__all__ = [
           'btce',
           'btcchina',
           'bitcurex',
           'bitfinex',
           'bitstamp',
           'campbx',
           'coinex',
           'cryptsy',
           'cryptotrade',
           'localbitcoins',
           'rocktrading',
           'justcoin',
           'bter',
           'coinse',
           'vircurex']
