__all__ = ['mtgox',
           'btce',
           'btcchina',
           'bitcurex',
           'bitfinex',
           'bitstamp',
           'campbx',
           'cryptotrade',
           'intersango',
           'localbitcoins',
           'rocktrading',
           'justcoin']
