#!/usr/bin/env python
# encoding: utf-8

from datetime import datetime

import models

base_url = "https://vircurex.com/api/"


class Vircurex(models.Exchange):
    """Docstring for Bitstamp """
    _markets_map = {"frc_ppc": "base=FRC&alt=PPC",
                    "frc_dgc": "base=FRC&alt=DGC",
                    "frc_usd": "base=FRC&alt=USD",
                    "frc_ltc": "base=FRC&alt=LTC",
                    "frc_xpm": "base=FRC&alt=XPM",
                    "frc_anc": "base=FRC&alt=ANC",
                    "frc_ixc": "base=FRC&alt=IXC",
                    "frc_trc": "base=FRC&alt=TRC",
                    "frc_dvc": "base=FRC&alt=DVC",
                    "frc_i0c": "base=FRC&alt=I0C",
                    "frc_ftc": "base=FRC&alt=FTC",
                    "frc_wdc": "base=FRC&alt=WDC",
                    "frc_nvc": "base=FRC&alt=NVC",
                    "frc_nmc": "base=FRC&alt=NMC",
                    "frc_btc": "base=FRC&alt=BTC",
                    "frc_eur": "base=FRC&alt=EUR",
                    "dgc_frc": "base=DGC&alt=FRC",
                    "dgc_i0c": "base=DGC&alt=I0C",
                    "dgc_usd": "base=DGC&alt=USD",
                    "dgc_xpm": "base=DGC&alt=XPM",
                    "dgc_anc": "base=DGC&alt=ANC",
                    "dgc_ixc": "base=DGC&alt=IXC",
                    "dgc_trc": "base=DGC&alt=TRC",
                    "dgc_dvc": "base=DGC&alt=DVC",
                    "dgc_ltc": "base=DGC&alt=LTC",
                    "dgc_ftc": "base=DGC&alt=FTC",
                    "dgc_ppc": "base=DGC&alt=PPC",
                    "dgc_nvc": "base=DGC&alt=NVC",
                    "dgc_nmc": "base=DGC&alt=NMC",
                    "dgc_btc": "base=DGC&alt=BTC",
                    "dgc_wdc": "base=DGC&alt=WDC",
                    "dgc_eur": "base=DGC&alt=EUR",
                    "usd_frc": "base=USD&alt=FRC",
                    "usd_dgc": "base=USD&alt=DGC",
                    "usd_wdc": "base=USD&alt=WDC",
                    "usd_ltc": "base=USD&alt=LTC",
                    "usd_xpm": "base=USD&alt=XPM",
                    "usd_anc": "base=USD&alt=ANC",
                    "usd_ixc": "base=USD&alt=IXC",
                    "usd_trc": "base=USD&alt=TRC",
                    "usd_dvc": "base=USD&alt=DVC",
                    "usd_i0c": "base=USD&alt=I0C",
                    "usd_ftc": "base=USD&alt=FTC",
                    "usd_ppc": "base=USD&alt=PPC",
                    "usd_nvc": "base=USD&alt=NVC",
                    "usd_nmc": "base=USD&alt=NMC",
                    "usd_btc": "base=USD&alt=BTC",
                    "usd_eur": "base=USD&alt=EUR",
                    "ltc_frc": "base=LTC&alt=FRC",
                    "ltc_dgc": "base=LTC&alt=DGC",
                    "ltc_usd": "base=LTC&alt=USD",
                    "ltc_xpm": "base=LTC&alt=XPM",
                    "ltc_anc": "base=LTC&alt=ANC",
                    "ltc_ixc": "base=LTC&alt=IXC",
                    "ltc_trc": "base=LTC&alt=TRC",
                    "ltc_dvc": "base=LTC&alt=DVC",
                    "ltc_i0c": "base=LTC&alt=I0C",
                    "ltc_ftc": "base=LTC&alt=FTC",
                    "ltc_ppc": "base=LTC&alt=PPC",
                    "ltc_nvc": "base=LTC&alt=NVC",
                    "ltc_nmc": "base=LTC&alt=NMC",
                    "ltc_btc": "base=LTC&alt=BTC",
                    "ltc_wdc": "base=LTC&alt=WDC",
                    "ltc_eur": "base=LTC&alt=EUR",
                    "xpm_frc": "base=XPM&alt=FRC",
                    "xpm_dgc": "base=XPM&alt=DGC",
                    "xpm_usd": "base=XPM&alt=USD",
                    "xpm_ltc": "base=XPM&alt=LTC",
                    "xpm_anc": "base=XPM&alt=ANC",
                    "xpm_ixc": "base=XPM&alt=IXC",
                    "xpm_trc": "base=XPM&alt=TRC",
                    "xpm_dvc": "base=XPM&alt=DVC",
                    "xpm_i0c": "base=XPM&alt=I0C",
                    "xpm_ftc": "base=XPM&alt=FTC",
                    "xpm_ppc": "base=XPM&alt=PPC",
                    "xpm_nvc": "base=XPM&alt=NVC",
                    "xpm_nmc": "base=XPM&alt=NMC",
                    "xpm_btc": "base=XPM&alt=BTC",
                    "xpm_wdc": "base=XPM&alt=WDC",
                    "xpm_eur": "base=XPM&alt=EUR",
                    "anc_frc": "base=ANC&alt=FRC",
                    "anc_dgc": "base=ANC&alt=DGC",
                    "anc_usd": "base=ANC&alt=USD",
                    "anc_xpm": "base=ANC&alt=XPM",
                    "anc_i0c": "base=ANC&alt=I0C",
                    "anc_ixc": "base=ANC&alt=IXC",
                    "anc_trc": "base=ANC&alt=TRC",
                    "anc_dvc": "base=ANC&alt=DVC",
                    "anc_ltc": "base=ANC&alt=LTC",
                    "anc_ftc": "base=ANC&alt=FTC",
                    "anc_ppc": "base=ANC&alt=PPC",
                    "anc_nvc": "base=ANC&alt=NVC",
                    "anc_nmc": "base=ANC&alt=NMC",
                    "anc_btc": "base=ANC&alt=BTC",
                    "anc_wdc": "base=ANC&alt=WDC",
                    "anc_eur": "base=ANC&alt=EUR",
                    "ixc_frc": "base=IXC&alt=FRC",
                    "ixc_dgc": "base=IXC&alt=DGC",
                    "ixc_usd": "base=IXC&alt=USD",
                    "ixc_ltc": "base=IXC&alt=LTC",
                    "ixc_xpm": "base=IXC&alt=XPM",
                    "ixc_anc": "base=IXC&alt=ANC",
                    "ixc_trc": "base=IXC&alt=TRC",
                    "ixc_dvc": "base=IXC&alt=DVC",
                    "ixc_i0c": "base=IXC&alt=I0C",
                    "ixc_ftc": "base=IXC&alt=FTC",
                    "ixc_ppc": "base=IXC&alt=PPC",
                    "ixc_nvc": "base=IXC&alt=NVC",
                    "ixc_nmc": "base=IXC&alt=NMC",
                    "ixc_btc": "base=IXC&alt=BTC",
                    "ixc_wdc": "base=IXC&alt=WDC",
                    "ixc_eur": "base=IXC&alt=EUR",
                    "trc_frc": "base=TRC&alt=FRC",
                    "trc_dgc": "base=TRC&alt=DGC",
                    "trc_usd": "base=TRC&alt=USD",
                    "trc_ltc": "base=TRC&alt=LTC",
                    "trc_xpm": "base=TRC&alt=XPM",
                    "trc_anc": "base=TRC&alt=ANC",
                    "trc_ixc": "base=TRC&alt=IXC",
                    "trc_dvc": "base=TRC&alt=DVC",
                    "trc_i0c": "base=TRC&alt=I0C",
                    "trc_ftc": "base=TRC&alt=FTC",
                    "trc_ppc": "base=TRC&alt=PPC",
                    "trc_nvc": "base=TRC&alt=NVC",
                    "trc_nmc": "base=TRC&alt=NMC",
                    "trc_btc": "base=TRC&alt=BTC",
                    "trc_wdc": "base=TRC&alt=WDC",
                    "trc_eur": "base=TRC&alt=EUR",
                    "dvc_frc": "base=DVC&alt=FRC",
                    "dvc_dgc": "base=DVC&alt=DGC",
                    "dvc_usd": "base=DVC&alt=USD",
                    "dvc_ltc": "base=DVC&alt=LTC",
                    "dvc_xpm": "base=DVC&alt=XPM",
                    "dvc_anc": "base=DVC&alt=ANC",
                    "dvc_ixc": "base=DVC&alt=IXC",
                    "dvc_trc": "base=DVC&alt=TRC",
                    "dvc_i0c": "base=DVC&alt=I0C",
                    "dvc_ftc": "base=DVC&alt=FTC",
                    "dvc_ppc": "base=DVC&alt=PPC",
                    "dvc_nvc": "base=DVC&alt=NVC",
                    "dvc_nmc": "base=DVC&alt=NMC",
                    "dvc_btc": "base=DVC&alt=BTC",
                    "dvc_wdc": "base=DVC&alt=WDC",
                    "dvc_eur": "base=DVC&alt=EUR",
                    "i0c_frc": "base=I0C&alt=FRC",
                    "i0c_dgc": "base=I0C&alt=DGC",
                    "i0c_usd": "base=I0C&alt=USD",
                    "i0c_xpm": "base=I0C&alt=XPM",
                    "i0c_anc": "base=I0C&alt=ANC",
                    "i0c_ixc": "base=I0C&alt=IXC",
                    "i0c_trc": "base=I0C&alt=TRC",
                    "i0c_dvc": "base=I0C&alt=DVC",
                    "i0c_ltc": "base=I0C&alt=LTC",
                    "i0c_ftc": "base=I0C&alt=FTC",
                    "i0c_ppc": "base=I0C&alt=PPC",
                    "i0c_nvc": "base=I0C&alt=NVC",
                    "i0c_nmc": "base=I0C&alt=NMC",
                    "i0c_btc": "base=I0C&alt=BTC",
                    "i0c_wdc": "base=I0C&alt=WDC",
                    "i0c_eur": "base=I0C&alt=EUR",
                    "ftc_frc": "base=FTC&alt=FRC",
                    "ftc_dgc": "base=FTC&alt=DGC",
                    "ftc_usd": "base=FTC&alt=USD",
                    "ftc_ltc": "base=FTC&alt=LTC",
                    "ftc_xpm": "base=FTC&alt=XPM",
                    "ftc_anc": "base=FTC&alt=ANC",
                    "ftc_ixc": "base=FTC&alt=IXC",
                    "ftc_trc": "base=FTC&alt=TRC",
                    "ftc_dvc": "base=FTC&alt=DVC",
                    "ftc_i0c": "base=FTC&alt=I0C",
                    "ftc_ppc": "base=FTC&alt=PPC",
                    "ftc_nvc": "base=FTC&alt=NVC",
                    "ftc_nmc": "base=FTC&alt=NMC",
                    "ftc_btc": "base=FTC&alt=BTC",
                    "ftc_wdc": "base=FTC&alt=WDC",
                    "ftc_eur": "base=FTC&alt=EUR",
                    "ppc_frc": "base=PPC&alt=FRC",
                    "ppc_dgc": "base=PPC&alt=DGC",
                    "ppc_usd": "base=PPC&alt=USD",
                    "ppc_ltc": "base=PPC&alt=LTC",
                    "ppc_xpm": "base=PPC&alt=XPM",
                    "ppc_anc": "base=PPC&alt=ANC",
                    "ppc_ixc": "base=PPC&alt=IXC",
                    "ppc_trc": "base=PPC&alt=TRC",
                    "ppc_dvc": "base=PPC&alt=DVC",
                    "ppc_i0c": "base=PPC&alt=I0C",
                    "ppc_ftc": "base=PPC&alt=FTC",
                    "ppc_wdc": "base=PPC&alt=WDC",
                    "ppc_nvc": "base=PPC&alt=NVC",
                    "ppc_nmc": "base=PPC&alt=NMC",
                    "ppc_btc": "base=PPC&alt=BTC",
                    "ppc_eur": "base=PPC&alt=EUR",
                    "nvc_frc": "base=NVC&alt=FRC",
                    "nvc_dgc": "base=NVC&alt=DGC",
                    "nvc_usd": "base=NVC&alt=USD",
                    "nvc_ltc": "base=NVC&alt=LTC",
                    "nvc_xpm": "base=NVC&alt=XPM",
                    "nvc_anc": "base=NVC&alt=ANC",
                    "nvc_ixc": "base=NVC&alt=IXC",
                    "nvc_trc": "base=NVC&alt=TRC",
                    "nvc_dvc": "base=NVC&alt=DVC",
                    "nvc_i0c": "base=NVC&alt=I0C",
                    "nvc_ftc": "base=NVC&alt=FTC",
                    "nvc_ppc": "base=NVC&alt=PPC",
                    "nvc_nmc": "base=NVC&alt=NMC",
                    "nvc_btc": "base=NVC&alt=BTC",
                    "nvc_wdc": "base=NVC&alt=WDC",
                    "nvc_eur": "base=NVC&alt=EUR",
                    "nmc_frc": "base=NMC&alt=FRC",
                    "nmc_dgc": "base=NMC&alt=DGC",
                    "nmc_usd": "base=NMC&alt=USD",
                    "nmc_ltc": "base=NMC&alt=LTC",
                    "nmc_xpm": "base=NMC&alt=XPM",
                    "nmc_anc": "base=NMC&alt=ANC",
                    "nmc_ixc": "base=NMC&alt=IXC",
                    "nmc_trc": "base=NMC&alt=TRC",
                    "nmc_dvc": "base=NMC&alt=DVC",
                    "nmc_i0c": "base=NMC&alt=I0C",
                    "nmc_ftc": "base=NMC&alt=FTC",
                    "nmc_ppc": "base=NMC&alt=PPC",
                    "nmc_nvc": "base=NMC&alt=NVC",
                    "nmc_btc": "base=NMC&alt=BTC",
                    "nmc_wdc": "base=NMC&alt=WDC",
                    "nmc_eur": "base=NMC&alt=EUR",
                    "btc_frc": "base=BTC&alt=FRC",
                    "btc_dgc": "base=BTC&alt=DGC",
                    "btc_usd": "base=BTC&alt=USD",
                    "btc_ltc": "base=BTC&alt=LTC",
                    "btc_xpm": "base=BTC&alt=XPM",
                    "btc_anc": "base=BTC&alt=ANC",
                    "btc_ixc": "base=BTC&alt=IXC",
                    "btc_trc": "base=BTC&alt=TRC",
                    "btc_dvc": "base=BTC&alt=DVC",
                    "btc_i0c": "base=BTC&alt=I0C",
                    "btc_ftc": "base=BTC&alt=FTC",
                    "btc_ppc": "base=BTC&alt=PPC",
                    "btc_nvc": "base=BTC&alt=NVC",
                    "btc_nmc": "base=BTC&alt=NMC",
                    "btc_wdc": "base=BTC&alt=WDC",
                    "btc_eur": "base=BTC&alt=EUR",
                    "wdc_frc": "base=WDC&alt=FRC",
                    "wdc_dgc": "base=WDC&alt=DGC",
                    "wdc_usd": "base=WDC&alt=USD",
                    "wdc_ltc": "base=WDC&alt=LTC",
                    "wdc_xpm": "base=WDC&alt=XPM",
                    "wdc_anc": "base=WDC&alt=ANC",
                    "wdc_ixc": "base=WDC&alt=IXC",
                    "wdc_trc": "base=WDC&alt=TRC",
                    "wdc_dvc": "base=WDC&alt=DVC",
                    "wdc_i0c": "base=WDC&alt=I0C",
                    "wdc_ftc": "base=WDC&alt=FTC",
                    "wdc_ppc": "base=WDC&alt=PPC",
                    "wdc_nvc": "base=WDC&alt=NVC",
                    "wdc_nmc": "base=WDC&alt=NMC",
                    "wdc_btc": "base=WDC&alt=BTC",
                    "wdc_eur": "base=WDC&alt=EUR",
                    "eur_frc": "base=EUR&alt=FRC",
                    "eur_dgc": "base=EUR&alt=DGC",
                    "eur_usd": "base=EUR&alt=USD",
                    "eur_ltc": "base=EUR&alt=LTC",
                    "eur_xpm": "base=EUR&alt=XPM",
                    "eur_anc": "base=EUR&alt=ANC",
                    "eur_ixc": "base=EUR&alt=IXC",
                    "eur_trc": "base=EUR&alt=TRC",
                    "eur_dvc": "base=EUR&alt=DVC",
                    "eur_i0c": "base=EUR&alt=I0C",
                    "eur_ftc": "base=EUR&alt=FTC",
                    "eur_ppc": "base=EUR&alt=PPC",
                    "eur_nvc": "base=EUR&alt=NVC",
                    "eur_nmc": "base=EUR&alt=NMC",
                    "eur_btc": "base=EUR&alt=BTC",
                    "eur_wdc": "base=EUR&alt=WDC",
                    }

    def __init__(self, market="ltc_btc"):
        """@todo: to be defined1

        :currency: @todo

        """
        self.market = market

    def depth(self):
        """@todo: Docstring for depth
        :returns: @todo

        """
        url = "".join([base_url, 'orderbook.json?', self._symbol])
        resp = self._request('GET', url).json()

        asks = []
        for p, a in resp['asks']:
            asks.append(models.Order(price=self._create_decimal(p),
                                     amount=self._create_decimal(a)))
        bids = []
        for p, a in resp['bids']:
            bids.append(models.Order(price=self._create_decimal(p),
                                     amount=self._create_decimal(a)))

        return asks, bids

    def ticker(self):
        """@todo: Docstring for ticker
        :returns: @todo

        """
        url = "".join([base_url, 'get_info_for_1_currency.json?', self._symbol])
        resp = self._request('GET', url).json()

        return models.Ticker(
                      last=self._create_decimal(resp['last_trade']),
                      buy=self._create_decimal(resp['highest_bid']),
                      sell=self._create_decimal(resp['lowest_ask']),
                      vol=self._create_decimal(resp['volume']),
                      )

    def trades(self):
        """@todo: Docstring for trades
        :returns: @todo

        """
        url = "".join([base_url, 'trades.json?', self._symbol])
        resp = self._request('GET', url).json()

        trades = []
        for t in resp:
            date = datetime.fromtimestamp(int(t['date']))
            amount = self._create_decimal(t['amount'])
            price = self._create_decimal(t['price'])
            tid = int(t['tid'])
            trades.append(models.Trade(date=date,
                                       amount=amount,
                                       price=price,
                                       tid=tid))

        return trades
